<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * h-0 h-2 h-4 h-6 h-8 h-10 h-12 h-14 h-16 h-18 h-20 h-22 h-24
 * md:h-0 md:h-2 md:h-4 md:h-6 md:h-8 md:h-10 md:h-12 md:h-14 md:h-16 md:h-18 md:h-20 md:h-22 md:h-24
 * lg:h-0 lg:h-2 lg:h-4 lg:h-6 lg:h-8 lg:h-10 lg:h-12 lg:h-14 lg:h-16 lg:h-18 lg:h-20 lg:h-22 lg:h-24
 * xl:h-0 xl:h-2 xl:h-4 xl:h-6 xl:h-8 xl:h-10 xl:h-12 lx:h-14 xl:h-16 xl:h-18 xl:h-20 xl:h-22 xl:h-24
 * 2xl:h-0 2xl:h-2 2xl:h-4 2xl:h-6 2xl:h-8 2xl:h-10 2xl:h-12 2lx:h-14 2xl:h-16 2xl:h-18 2xl:h-20 2xl:h-22 2xl:h-24
 */


$block_name = 'spacer';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Spacer default classes
$spacer_default_classes = 'not-prose relative border-y-0';

// Spacer border default classes
$spacer_border_classes = 'after:absolute after:top-[50%] after:translate-y-[-50%] after:w-full after:h-[1px]';

//
$spacer = $spacer_md = $spacer_lg = $spacer_xl = $spacer_2xl = $spacer_style_classes = '';

//
$root_spacer = 'h-';

if( get_field('spacer') !== 0 && get_field('spacer') !== 'default' ) $spacer = $root_spacer.(get_field('spacer')*2);
if( get_field('spacer_md') !== 'default' ) $spacer_md = 'md:'.$root_spacer.(get_field('spacer_md')*2);
if( get_field('spacer_lg') !== 'default' ) $spacer_lg = 'lg:'.$root_spacer.(get_field('spacer_lg')*2);
if( get_field('spacer_xl') !== 'default' ) $spacer_xl = 'xl:'.$root_spacer.(get_field('spacer_xl')*2);
if( get_field('spacer_2xl') !== 'default' ) $spacer_2xl = '2xl:'.$root_spacer.(get_field('spacer_2xl')*2);

if(get_field('spacer_style') == 'light'){
	$spacer_style_classes = $spacer_border_classes.' after:bg-black/10';
} elseif(get_field('spacer_style') == 'dark'){
	$spacer_style_classes = 'border-t border-gray-600';
} else{
	$spacer_style_classes = 'border-none';
}

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
	$spacer_default_classes,
	$spacer,
	$spacer_md,
	$spacer_lg,
	$spacer_xl,
	$spacer_2xl,
	$spacer_style_classes,
);

$classes = implode( ' ', $all_classes );

?>

<hr class="<?php echo $classes ?>" />
