<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[mdi-light--check] icon-[mdi-light--chevron-right] icon-[mdi-light--chevron-double-right]
 *
 */


$block_name = 'service-highlights';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

?>

<?php if( have_rows('plan_highlights') ): ?>

	<div class="shadow-xl border-2 border-white rounded-xl overflow-hidden">
		<div class="flex flex-row bg-linear-to-b from-primary to-primary-dark">
			<div class="px-3 xl:px-6 py-4 w-full md:basis-1/4">
				<h3 class="mt-0 font-bold text-white text-xl"><span class="hidden md:block">Service Plan</span> <span class="md:hidden">Service Plans & Key Features</span></h3>
			</div>
			<div class="hidden md:block px-3 xl:px-6 py-4 w-full md:basis-3/4">
				<h3 class="mt-0 font-bold text-white text-xl">Key Features</h3>
			</div>
		</div>

		<?php while( have_rows('plan_highlights') ) : the_row(); ?>
			<div class="flex md:flex-row flex-col bg-white border-neutral border-b-1 last:border-b-0">
				<div class="px-3 xl:px-6 py-2 md:py-4 xl:py-6 border-neutral border-r-1 w-full font-semibold text-primary-dark md:basis-1/4">
					<span class="font-bold text-lg"><?php echo get_sub_field('plan') ?></span>
				</div>
				<div class="**:!mb-0 px-3 xl:px-6 py-2 md:py-4 xl:py-6 w-full font-sans md:basis-3/4">
					<?php echo get_sub_field('plan_feature') ?>
				</div>
			</div>
		<?php endwhile ?>
	</div>

<?php endif; ?>
