<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[mdi-light--check] icon-[mdi-light--chevron-right] icon-[mdi-light--chevron-double-right]
 * icon-[line-md--my-location-loop] icon-[line-md--phone-call-twotone-loop] icon-[line-md--cloud-alt-upload-twotone-loop]
 * icon-[line-md--hazard-lights-off-filled-loop] icon-[line-md--hazard-lights-off-filled-loop] icon-[line-md--gauge-twotone-loop] icon-[line-md--chat-round-dots-twotone]
 * icon-[line-md--speed-twotone-loop] icon-[line-md--speedometer-loop] icon-[line-md--alert-twotone-loop] icon-[line-md--cog-loop] size-40
 *
 */


$block_name = 'list';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Block color
$color = ( empty( $block['textColor'] ) ) ? '' : 'has-' . $block['textColor'] . '-color';

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$color,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

// Pass into template part for re-using outside of Block
get_template_part( 'template-parts/components/list', null, array('classes' => $classes, 'anchor' => $anchor ) );

?>

