<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * my-2 my-4 my-6 my-8 my-10 my-12 my-14 my-16 my-18 my-20 my-22 my-24
 * md:my-2 md:my-4 md:my-6 md:my-8 md:my-10 md:my-12 md:my-14 md:my-16 md:my-18 md:my-20 md:my-22 md:my-24
 * lg:my-2 lg:my-4 lg:my-6 lg:my-8 lg:my-10 lg:my-12 lg:my-14 lg:my-16 lg:my-18 lg:my-20 lg:my-22 lg:my-24
 * xl:my-2 xl:my-4 xl:my-6 xl:my-8 xl:my-10 xl:my-12 lx:my-14 xl:my-16 xl:my-18 xl:my-20 xl:my-22 xl:my-24
 * 2xl:my-2 2xl:my-4 2xl:my-6 2xl:my-8 2xl:my-10 2xl:my-12 2lx:my-14 2xl:my-16 2xl:my-18 2xl:my-20 2xl:my-22 2xl:my-24
 * !mb-0
 */


$block_name = 'card';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Card default classes
$card_default_classes = 'content-card';

if( get_field('style') === 'light' ){
	$card_styles = 'content-card-light overflow-hidden border-2 border-white rounded-xl bg-tertiary shadow-xl';
} elseif( get_field('style') === 'dark' ){
	$card_styles = 'content-card-dark overflow-hidden border-2 border-white rounded-xl bg-linear-to-b from-primary to-primary-dark shadow-xl';
} else{
	$card_styles = 'content-card-accent overflow-hidden border-2 border-white rounded-xl bg-secondary shadow-xl';
}

if( get_field('size') === 'jumbo' ){
	$card_size = 'p-8 md:p-12 lg:p-16 2xl:p-20';
} elseif( get_field('size') === 'full' ){
	$card_size = 'p-8 h-full';
} else{
	$card_size = 'p-8';
}

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
	$card_default_classes,
	$card_styles,
	$card_size
);

$classes = implode( ' ', $all_classes );

?>

<div <?php echo esc_attr( $anchor ); ?> class="<?php echo $classes ?>">
	<InnerBlocks class="space-y-3" />
</div>

