<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[mdi-light--check] icon-[mdi-light--chevron-right] icon-[mdi-light--chevron-double-right]
 *
 */


$block_name = 'service-table';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

$gold_title = get_field('gold_title','option') ?: '';
$silver_title = get_field('silver_title','option') ?: '';
$bronze_title = get_field('bronze_title','option') ?: '';

$gold_cost = get_field('gold_cost','option') ?: '';
$silver_cost = get_field('silver_cost','option') ?: '';
$bronze_cost = get_field('bronze_cost','option') ?: '';

?>

<?php if( have_rows('plan_details','option') ): ?>

	<div>
		<div class="hidden md:flex md:flex-row flex-col">
			<div class="w-full md:basis-2/5 2xl:basis-1/4">
			</div>
			<div class="w-full md:basis-1/5 2xl:basis-1/4">
				<div class="bg-white py-4 border-1 border-neutral border-r-0 border-b-5 border-b-amber-400 rounded-t-xl h-full text-center">
					<h3 class="font-bold text-primary-dark h6">Gold</h3>
					<span class="block text-sm 2xl:text-base"><?php echo $gold_title; ?></span>
					<span class="block mt-1 font-semibold text-primary-dark"><?php echo $gold_cost; ?></span>
				</div>
			</div>
			<div class="w-full md:basis-1/5 2xl:basis-1/4">
				<div class="bg-white py-4 border-1 border-neutral border-r-0 border-b-5 border-b-slate-400 rounded-t-xl h-full text-center">
					<h3 class="font-bold text-primary-dark h6">Silver</h3>
					<span class="block text-sm 2xl:text-base"><?php echo $silver_title; ?></span>
					<span class="block mt-1 font-semibold text-primary-dark"><?php echo $silver_cost; ?></span>
				</div>
			</div>
			<div class="w-full md:basis-1/5 2xl:basis-1/4">
				<div class="bg-white py-4 border-1 border-neutral border-b-5 border-b-yellow-700 rounded-t-xl h-full text-center">
					<h3 class="font-bold text-primary-dark h6">Bronze</h3>
					<span class="block text-sm 2xl:text-base"><?php echo $bronze_title; ?></span>
					<span class="block mt-1 font-semibold text-primary-dark"><?php echo $bronze_cost; ?></span>
				</div>
			</div>
		</div>

		<div class="bg-white border-1 border-neutral rounded-xl md:rounded-tr-none overflow-hidden">
			<?php while( have_rows('plan_details','option') ) : the_row(); ?>
				<div class="flex md:flex-row flex-col border-neutral last:border-0 border-b-1">
					<div class="flex items-center bg-neutral md:bg-white px-3 py-4 border-neutral border-r-1 last:border-r-0 w-full md:basis-2/5 2xl:basis-1/4">
						<span class="block font-semibold text-primary-dark"><?php echo get_sub_field('plan_feature') ?></span>
					</div>
					<div class="items-center self-center px-3 py-4 border-neutral md:border-r-1 border-b-1 md:border-b-0 last:border-b-0 w-full text-center md:basis-1/5 2xl:basis-1/4">
						<span class="md:hidden block font-semibold text-lg">Gold</span>
						<?php if( in_array("gold", get_sub_field('plan_checked')) ): ?>
							<span class="size-8 text-primary icon-[material-symbols--check-circle]"></span>
						<?php endif ?>
					</div>
					<div class="self-center px-3 py-4 border-neutral md:border-r-1 border-b-1 md:border-b-0 last:border-b-0 w-full text-center md:basis-1/5 2xl:basis-1/4">
						<span class="md:hidden block font-semibold text-lg">Silver</span>
						<?php if( in_array("silver", get_sub_field('plan_checked')) ): ?>
							<span class="size-8 text-primary icon-[material-symbols--check-circle]"></span>
						<?php else: ?>
							<span class="size-8 text-tertiary icon-[mdi--close-circle]"></span>
						<?php endif ?>
					</div>
					<div class="self-center px-3 py-4 border-neutral w-full text-center md:basis-1/5 2xl:basis-1/4">
						<span class="md:hidden block font-semibold text-lg">Bronze</span>
						<?php if( in_array("bronze", get_sub_field('plan_checked')) ): ?>
							<span class="size-8 text-primary icon-[material-symbols--check-circle]"></span>
						<?php else: ?>
							<span class="size-8 text-tertiary icon-[mdi--close-circle]"></span>
						<?php endif ?>
					</div>
				</div>
			<?php endwhile; ?>
		</div>
	</div>

<?php endif; ?>
